import{S,a as I,i as l}from"./assets/vendor-DyqkKiSr.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const q=document.querySelector(".gallery");let M=new S(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function f(t){return t.map(({webformatURL:r,largeImageURL:o,tags:a,likes:e,views:s,comments:n,downloads:E})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${r}" alt="${a}" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="title">Likes</h2><p class="amount">${e}</p></div>
          <div class="block"><h2 class="title">Views</h2><p class="amount">${s}</p></div>
          <div class="block"><h2 class="title">Comments</h2><p class="amount">${n}</p></div>
          <div class="block"><h2 class="title">Downloads</h2><p class="amount">${E}</p></div>
        </div>
      </li>`).join("")}function y(){M.refresh()}function k(){const t=q.lastElementChild;t&&t.scrollIntoView({behavior:"smooth",block:"end"})}const P="49393685-3ee93529131780612454ef79e",$="https://pixabay.com/api/";async function p(t,r=1){var o,a;try{return(await I.get($,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(e){throw new Error(((a=(o=e.response)==null?void 0:o.data)==null?void 0:a.message)||"Failed to fetch images")}}function g(){document.querySelectorAll(".gallery-item").forEach(r=>{r.style.width="";const o=Math.floor(Math.random()*176)+275;r.style.width=`${o}px`})}const L=document.querySelector(".form"),m=document.querySelector(".gallery"),h=document.querySelector(".loader"),i=document.querySelector(".btn2");let c=1,u="";const b=15;h.style.display="none";i.classList.add("is-hidden");function v(){h.style.display="block"}function d(){h.style.display="none"}async function x(t){if(t.preventDefault(),m.innerHTML="",v(),i.classList.add("is-hidden"),u=t.target.elements["search-text"].value.trim(),c=1,!u){l.error({title:"Error",message:"Input cannot be empty!",color:"#ff0000"}),d();return}try{const r=await p(u,c);if(d(),!r.hits.length){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}m.innerHTML=f(r.hits),g(),y(),r.totalHits>c*b&&i.classList.remove("is-hidden"),L.reset()}catch(r){d(),l.error({title:"Error",message:r.message})}}async function w(){v(),c++;try{const t=await p(u,c);d(),(!t.hits.length||t.hits.length<b)&&(i.classList.add("is-hidden"),i.removeEventListener("click",w),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),m.insertAdjacentHTML("beforeend",f(t.hits)),g(),y(),k()}catch(t){d(),l.error({title:"Error",message:t.message})}}L.addEventListener("submit",x);i.addEventListener("click",w);
//# sourceMappingURL=index.js.map
